In [107]:
import numpy as np

A = np.random.randn(10,5)

U, S, V = np.linalg.svd(A, full_matrices=False)

In [142]:
K=5
Up = np.random.randn(10,K)
Vp = np.random.randn(5,K)
alpha=0.1

for epoch in range(1000):
    for r in range(A.shape[0]):
        for c in range(A.shape[1]):
            e = A[r][c] - Up[r]@Vp[c]
            for k in range(K):
                urk = Up[r][k] + alpha*e*Vp[c][k]
                vck = Vp[c][k] + alpha*e*Up[r][k]
                Up[r][k] = urk
                Vp[c][k] = vck
    if epoch%100 == 0:
        print('epoch:', epoch, 'error:', ((A - Up@Vp.transpose())**2).sum())

print('Final error:', ((A - Up@Vp.transpose())**2).sum())



epoch: 0 error: 24.439271509210702
epoch: 100 error: 0.00030857084498882076
epoch: 200 error: 5.223368157722497e-08
epoch: 300 error: 6.9039267735843186e-12
epoch: 400 error: 6.937521782191437e-16
epoch: 500 error: 9.320974803464273e-20
epoch: 600 error: 1.774298088957813e-23
epoch: 700 error: 3.008113254219329e-27
epoch: 800 error: 1.099802294742331e-29
epoch: 900 error: 7.522730511025153e-30
Final error: 7.247274380729169e-30


In [143]:
un = np.sqrt((Up**2).sum(0))
vn = np.sqrt((Vp**2).sum(0))
Up = Up / un
Vp = Vp / vn

print(un, vn)
Sp = un*vn

print(S)
print(np.sort(Sp)[::-1])

print(U)
print(Up)

[2.20231548 2.18348705 2.97982565 2.34213706 2.69968518] [1.38920807 2.19355921 1.33427376 1.42352847 0.99820064]
[3.4836438  3.04456959 2.5842056  2.16345772 1.78844635]
[4.78960813 3.97590316 3.33409878 3.05947443 2.69482748]
[[-0.18245985  0.18418082  0.24778106  0.40483081  0.0912672 ]
 [ 0.66453521 -0.05733598 -0.11123814  0.09319504 -0.54435347]
 [ 0.38920569 -0.38928931 -0.13648041 -0.40378101  0.2125861 ]
 [-0.09094689 -0.39311641  0.02633289  0.19701024  0.09686905]
 [-0.49576339  0.01524406 -0.50743534 -0.20024927 -0.51418957]
 [-0.02896487 -0.14858486 -0.53135408 -0.03754665  0.22786475]
 [-0.14519012 -0.67843343  0.30159583  0.05387275 -0.02064156]
 [ 0.07969707 -0.12897956  0.04063128  0.48574855 -0.42283443]
 [ 0.22552797  0.11615255 -0.457354    0.50894822  0.38108342]
 [ 0.20108205  0.37946599  0.25553647 -0.29356911  0.00450226]]
[[-0.44394447  0.03013626 -0.05301823 -0.08584529  0.0308439 ]
 [ 0.34476172 -0.479814   -0.14266644  0.42725288 -0.41435171]
 [ 0.58551894  